website/google/urls.py
from django.urls import path
from . import views 

urlpatterns =[
    path("", views.index, name="index"),
    # path("<str:name>", views.greet, name="greet"),
    path("<int:birth>", views.birth, name="birth"),
    # path("christmas",views.christmas, name="christmas")
]

website/newyear/urls.py
from django.urls import path
from . import views

app_name= "newyear"

urlpatterns =[
    path("", views.index, name="index")
]

website/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

website/website/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('google/', include("google.urls")),
    path('tasks/', include("tasks.urls")),
    path('newyear/', include("newyear.urls")),
]

website/google/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
import datetime
# Create your views here.

app_name ="google"

def index(request):
    return HttpResponse("Hello World!")

# def greet(request ,name):
#     return HttpResponse(f"Hello, {name}!".title())

def greet(request, name):
    return render (request, 'hello/index.html', {
        "name" : name.title()
    })

# def christmas(request):
#     now = datetime.datetime.now()
#     return render(request, 'hello/index.html', {
#         "christmas" : now.month == 1 and now.day == 1 
#     })    

def birth(request, birth):
    today = datetime.datetime.now()
    return render(request, 'hello/index.html' ,{
        "age" : today.year - birth
    })

website/newyear/views.py
from django.shortcuts import render
from . import views
import datetime
# Create your views here.

app_name = "newyear"

def index(request):
    return render (request, "newyear/index.html", {
        "now" : datetime.datetime.now()
    })

website/tasks/views.py
from django.shortcuts import render
from django import forms

# Create your views here.

tasks = ["Check Email", "Make Files", "Run As Administartor"]


def index(request):
    return render(request, "tasks/index.html", {
        "tasks": tasks
    })


def add(request):
    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })


class NewTaskForm(forms.Form):
    task = forms.CharField(label="Add Task")

website/google/templates/hello/index.html
 {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'hello/style.css' %}">
    <title>Is it christmas?</title>
</head>

<body>
    <!-- <h1>Hello {{name}}</h1> -->
    <h1>You are {{age}} years</h1>
    <!-- {% if christmas %}
    <h1>YES</h1>
    {% else %}
    <h1>NO</h1>
    {% endif %} -->
</body>

</html>

website/newyear/templates/newyear/index.html
{% extends 'newyear/layout.html' %}

{% block content %}
<h1>Hi from New Year index.html</h1>
{% endblock %}

website/newyear/templates/newyear/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'newyear/style.css' %}">
    <title>New Year</title>
</head>
<body>
    {% block content %}
    <h1>Hello From New Year 'layout'</h1>
    {% endblock %}
</body>
</html>

website/tasks/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=\, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'tasks/style.css' %}">
    <title>Tasks</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

website/tasks/templates/tasks/add.html
{% extends 'tasks/layout.html' %}
{% block content %}
<form method="post">
  {% csrf_token %} {{ form }}
  <input type="submit" />
</form>
<a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

website/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %} 
{% block content %}
<ul>
  {% for task in tasks %}
  <li>{{ task }}</li>
  {% endfor %}
</ul>
<a href="{% url 'tasks:add' %}">Add Task</a>

{% endblock %}

website/tasks/templates/tasks/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'tasks/style.css' %}">
    <title>Tasks</title>
</head>
<body>
    <h1>Tasks</h1>
    {% block content %}
    {% endblock %}
</body>
</html>